runtime: go
api_version: go1

handlers:
  - url: /api/.*
    script: _go_app

  - url: /(|top$)
    static_files: public/index.html
    upload: public/index.html

  - url: /rss/.+
    static_files: public/index.html
    upload: public/index.html

  - url: /
    static_dir: public

env_variables:
   RSS_URL : http://feeds.rebuild.fm/rebuildfm
   TARGET_FIELD: title
   REGEXP: higepon
